# Generated by Django 5.2 on 2025-04-19 19:01

import Account.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='اسم الشركة')),
                ('name_of_responsible_person', models.CharField(max_length=50, verbose_name='اسم الشخص المسؤول')),
                ('phone_number', models.CharField(max_length=50, verbose_name='رقم الهاتف')),
                ('state', models.CharField(max_length=50, verbose_name='الولاية')),
                ('governorate', models.CharField(max_length=50, verbose_name='المحافظة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=Account.models.uploade_logo, verbose_name='شعار الشركة')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='الرابط الفريد')),
            ],
            options={
                'verbose_name': 'قائمة الملف الشخصي للشركة',
                'verbose_name_plural': 'قائمة الملف الشخصي للشركة',
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الفئة الوظيفية')),
                ('icon_class', models.CharField(blank=True, help_text='أدخل اسم أيقونة FontAwesome أو Bootstrap Icons', max_length=100, null=True, verbose_name='اسم الأيقونة')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='الرابط الفريد')),
            ],
            options={
                'verbose_name': 'فئات الوظيفية',
                'verbose_name_plural': ' فئات الوظيفية',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=Account.models.uploade_image, verbose_name='الصورة الشخصية')),
                ('data_of_brith', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='الموقع')),
                ('gender', models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى'), ('unspecified', 'غير محدد')], max_length=50, null=True, verbose_name='الجنس')),
                ('nationality', models.CharField(blank=True, choices=[('سوريا', 'سوريا'), ('لبنان', 'لبنان'), ('الأردن', 'الأردن'), ('فلسطين', 'فلسطين'), ('العراق', 'العراق'), ('السعودية', 'السعودية'), ('الإمارات', 'الإمارات'), ('قطر', 'قطر'), ('الكويت', 'الكويت'), ('البحرين', 'البحرين'), ('عمان', 'عمان'), ('اليمن', 'اليمن'), ('مصر', 'مصر'), ('ليبيا', 'ليبيا'), ('السودان', 'السودان'), ('تونس', 'تونس'), ('الجزائر', 'الجزائر'), ('المغرب', 'المغرب'), ('موريتانيا', 'موريتانيا'), ('تركيا', 'تركيا'), ('إيران', 'إيران'), ('أفغانستان', 'أفغانستان'), ('باكستان', 'باكستان'), ('الهند', 'الهند'), ('الصين', 'الصين'), ('اليابان', 'اليابان'), ('كوريا الجنوبية', 'كوريا الجنوبية'), ('ماليزيا', 'ماليزيا'), ('إندونيسيا', 'إندونيسيا'), ('تايلاند', 'تايلاند'), ('فيتنام', 'فيتنام'), ('الفلبين', 'الفلبين'), ('فرنسا', 'فرنسا'), ('ألمانيا', 'ألمانيا'), ('إيطاليا', 'إيطاليا'), ('إسبانيا', 'إسبانيا'), ('بريطانيا', 'بريطانيا'), ('السويد', 'السويد'), ('النرويج', 'النرويج'), ('الدنمارك', 'الدنمارك'), ('سويسرا', 'سويسرا'), ('اليونان', 'اليونان'), ('هولندا', 'هولندا'), ('بلجيكا', 'بلجيكا'), ('النمسا', 'النمسا'), ('البرتغال', 'البرتغال'), ('بولندا', 'بولندا'), ('التشيك', 'التشيك'), ('روسيا', 'روسيا'), ('الولايات المتحدة', 'الولايات المتحدة'), ('كندا', 'كندا'), ('المكسيك', 'المكسيك'), ('البرازيل', 'البرازيل'), ('الأرجنتين', 'الأرجنتين'), ('كولومبيا', 'كولومبيا'), ('تشيلي', 'تشيلي'), ('بيرو', 'بيرو'), ('فنزويلا', 'فنزويلا'), ('جنوب أفريقيا', 'جنوب أفريقيا'), ('نيجيريا', 'نيجيريا'), ('كينيا', 'كينيا'), ('إثيوبيا', 'إثيوبيا'), ('غانا', 'غانا'), ('السنغال', 'السنغال'), ('أستراليا', 'أستراليا'), ('نيوزيلندا', 'نيوزيلندا')], max_length=50, null=True, verbose_name='الجنسية')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='الولاية')),
                ('governorate', models.CharField(blank=True, max_length=50, null=True, verbose_name='المحافظة')),
                ('phone_Number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف')),
                ('minimum_salary', models.CharField(blank=True, max_length=50, null=True, verbose_name='الراتب الأدنى')),
                ('Number_of_years_of_experience', models.IntegerField(blank=True, null=True, verbose_name='عدد سنوات الخبرة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('the_biography', models.FileField(blank=True, max_length=200, null=True, upload_to='uploads/cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), Account.models.validate_file_size], verbose_name='السيرة الذاتية')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='الرابط الفريد')),
            ],
            options={
                'verbose_name': 'قائمة الملف الشخصي للباحث ',
                'verbose_name_plural': 'قائمة الملف الشخصي للباحث',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='اسم الوظيفة')),
                ('job_description', models.TextField(verbose_name='وصف الوظيفة')),
                ('career_type', models.CharField(choices=[('full_time', 'دوام كامل'), ('part_time', 'دوام جزئي'), ('contract', 'عقد'), ('temporary', 'وظيفة مؤقتة'), ('freelance', 'عمل حر'), ('internship', 'تدريب'), ('remote', 'عمل عن بُعد'), ('on_site', 'عمل مكتبي')], max_length=255, verbose_name='نوع الوظيفة')),
                ('education', models.CharField(choices=[('high_school', 'الثانوية العامة أو ما يعدلها (High School)'), ('bachelor', "جامعي (بكالوريوس / ليسانس) (Bachelor's Degree)"), ('master', "ماجستير (Master's Degree)"), ('phd', 'دكتوراه (PhD)'), ('diploma_3_years', 'دبلوم 3 سنوات (3-Year Diploma)'), ('diploma_5_years', 'دبلوم 5 سنوات (5-Year Diploma)'), ('higher_diploma', 'دبلوم عالي (Higher Diploma)'), ('associate_degree', 'دبلوم مساعد (Associate Degree)'), ('postgraduate', 'دراسات ما بعد التخرج (Postgraduate Studies)'), ('professional_certificate', 'شهادة مهنية (Professional Certificate)'), ('vocational_training', 'تدريب مهني (Vocational Training)'), ('other', 'آخر (Other)')], max_length=255, verbose_name='المستوى التعليمي')),
                ('career_level', models.CharField(choices=[('intern', 'متدرب'), ('entry', 'مبتدئ'), ('mid', 'متوسط الخبرة'), ('senior', 'متقدم الخبرة'), ('manager', 'مدير'), ('director', 'مدير تنفيذي'), ('vp', 'نائب الرئيس'), ('freelance', 'عمل حر'), ('consultant', 'مستشار'), ('executive', 'تنفيذي'), ('ceo', 'المدير التنفيذي (CEO)'), ('coo', 'المدير العملياتي (COO)'), ('cto', 'المدير التقني (CTO)'), ('founder', 'مؤسس')], max_length=255, verbose_name='المستوى الوظيفي')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى'), ('unspecified', 'غير محدد')], max_length=255, verbose_name='الجنس')),
                ('years_of_experience_from', models.IntegerField(verbose_name='سنوات الخبرة (من)')),
                ('years_of_experience_to', models.IntegerField(verbose_name='سنوات الخبرة (إلى)')),
                ('salary', models.CharField(max_length=255, verbose_name='الراتب')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone_number', models.CharField(max_length=255, verbose_name='رقم الهاتف')),
                ('publication_date', models.DateField(verbose_name='تاريخ النشر')),
                ('closing_date', models.DateField(verbose_name='تاريخ الإغلاق')),
                ('location', models.CharField(max_length=255, verbose_name='الموقع')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='الرابط الفريد')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='Account.employerprofile', verbose_name='صاحب العمل')),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.jobcategory', verbose_name='الفئة الوظيفية')),
            ],
            options={
                'verbose_name': 'وظيفة',
                'verbose_name_plural': 'الوظائف',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='اسم المتقدم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=10, verbose_name='حالة الطلب')),
                ('cv_link', models.URLField(blank=True, null=True, verbose_name='رابط السيرة الذاتية')),
                ('cover_letter', models.TextField(blank=True, null=True, verbose_name='خطاب التقديم')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ الإنشاء')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Account.jobs', verbose_name='الوظيفة')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Account.userprofile', verbose_name='الباحث عن العمل')),
            ],
            options={
                'verbose_name': 'طلب توظيف',
                'verbose_name_plural': 'طلبات التوظيف',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_Name_Link', models.CharField(blank=True, max_length=70, null=True, verbose_name='رابط أو اسم المشروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('project_description', models.TextField(blank=True, null=True, verbose_name='وصف المشروع')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile', verbose_name='اسم الملف الشخصي')),
            ],
            options={
                'verbose_name': 'قائمة المشاريع ',
                'verbose_name_plural': 'قائمة  المشاريع',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(blank=True, choices=[('العربية', 'العربية'), ('الإنجليزية', 'الإنجليزية'), ('الفرنسية', 'الفرنسية'), ('التركية', 'التركية'), ('الإسبانية', 'الإسبانية'), ('الألمانية', 'الألمانية'), ('الإيطالية', 'الإيطالية'), ('البرتغالية', 'البرتغالية'), ('الروسية', 'الروسية'), ('الصينية', 'الصينية'), ('اليابانية', 'اليابانية'), ('الكورية', 'الكورية'), ('الهندية', 'الهندية'), ('الأوردو', 'الأوردو'), ('الفارسية', 'الفارسية'), ('العبرية', 'العبرية'), ('البنغالية', 'البنغالية'), ('التايلاندية', 'التايلاندية'), ('الهولندية', 'الهولندية'), ('اليونانية', 'اليونانية'), ('السويدية', 'السويدية'), ('الدنماركية', 'الدنماركية'), ('النرويجية', 'النرويجية'), ('الفنلندية', 'الفنلندية'), ('البولندية', 'البولندية'), ('التشيكية', 'التشيكية'), ('الرومانية', 'الرومانية'), ('المجرية', 'المجرية'), ('التاميلية', 'التاميلية'), ('التيلوجو', 'التيلوجو'), ('الماليزية', 'الماليزية'), ('الإندونيسية', 'الإندونيسية'), ('الفلبينية', 'الفلبينية'), ('الفيتنامية', 'الفيتنامية'), ('السواحلية', 'السواحلية')], max_length=50, null=True, verbose_name='اللغة')),
                ('language_lavel', models.CharField(blank=True, choices=[('لغة الأم', 'لغة الأم'), ('ضعيف', 'ضعيف'), ('مبتدئ', 'مبتدئ'), ('متوسط', 'متوسط'), ('جيد جداً', 'جيد جداً'), ('ممتاز', 'ممتاز'), ('متقدم', 'متقدم'), ('خبير', 'خبير')], max_length=50, null=True, verbose_name='مستوى اللغة')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile', verbose_name='اسم الملف الشخصي')),
            ],
            options={
                'verbose_name': 'قائمة اللغات ',
                'verbose_name_plural': 'قائمة  اللغات',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(blank=True, max_length=70, null=True, verbose_name='المسمى الوظيفي')),
                ('Company_Name', models.CharField(blank=True, max_length=70, null=True, verbose_name='اسم الشركة')),
                ('Company_location', models.CharField(blank=True, max_length=70, null=True, verbose_name='موقع الشركة')),
                ('From_history', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('To_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='Account.userprofile', verbose_name='اسم الملف الشخصي')),
            ],
            options={
                'verbose_name': 'قائمة الخبرات ',
                'verbose_name_plural': 'قائمة  الخبرات',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_degree', models.CharField(blank=True, choices=[('لم أكمل التعليم', 'لم أكمل التعليم'), ('التعليم الأساسي', 'التعليم الأساسي'), ('الثانوية العامة أو ما يعادلها', 'الثانوية العامة أو ما يعادلها'), ('دبلوم سنتين', 'دبلوم سنتين'), ('دبلوم 3 سنوات', 'دبلوم 3 سنوات'), ('دبلوم 5 سنوات', 'دبلوم 5 سنوات'), ('دبلوم عالي', 'دبلوم عالي'), ('جامعي (بكالوريوس / ليسانس)', 'جامعي (بكالوريوس / ليسانس)'), ('ماجستير', 'ماجستير'), ('دكتوراه', 'دكتوراه'), ('دكتوراه ما بعد التخصص', 'دكتوراه ما بعد التخصص'), ('بروفيسور', 'بروفيسور'), ('شهادة مهنية', 'شهادة مهنية'), ('دورة تدريبية متخصصة', 'دورة تدريبية متخصصة')], max_length=50, null=True, verbose_name='الدرجة الأكاديمية')),
                ('institute_university', models.CharField(blank=True, max_length=50, null=True, verbose_name='المعهد / الجامعة')),
                ('Domain', models.CharField(blank=True, max_length=50, null=True, verbose_name='التخصص')),
                ('Appreciation', models.CharField(blank=True, max_length=50, null=True, verbose_name='التقدير')),
                ('Year_of_completion_or_graduation', models.DateField(blank=True, null=True, verbose_name='سنة التخرج أو الإكمال')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile', verbose_name='اسم الملف الشخصي')),
            ],
            options={
                'verbose_name': 'قائمة التعليم  ',
                'verbose_name_plural': 'قائمة  التعليم ',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='اسم الشهادة')),
                ('Donor', models.CharField(blank=True, max_length=70, null=True, verbose_name='الجهة المانحة')),
                ('Date', models.DateField(blank=True, null=True, verbose_name='تاريخ المنح')),
                ('Certificate_description', models.TextField(blank=True, null=True, verbose_name='وصف الشهادة')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile', verbose_name='اسم الملف الشخصي')),
            ],
            options={
                'verbose_name': 'قائمة الشهادات ',
                'verbose_name_plural': 'قائمة  الشهادات',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('jobSeeker', 'Job Seeker'), ('employer_company', 'Employer Company')], default='jobSeeker', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='تم قراءته؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.application', verbose_name='الطلب')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'الاشعارات',
                'verbose_name_plural': 'الاشعارات',
            },
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userEmployer', to=settings.AUTH_USER_MODEL, verbose_name='اسم المستخدم'),
        ),
    ]
