# Generated by Django 5.2 on 2025-04-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('jobSeeker', 'Job Seeker'), ('employer_company', 'Employer Company')], max_length=50),
        ),
    ]
