# Generated by Django 5.2 on 2025-05-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='اسم الفئة الوظيفية'),
        ),
    ]
