# Generated by Django 5.2 on 2025-05-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_jobcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(error_messages={'unique': 'فئة وظيفية بهذا الاسم موجودة بالفعل.'}, max_length=50, unique=True, verbose_name='اسم الفئة الوظيفية'),
        ),
    ]
